
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    platform: linux/amd64
    volumes:
      - ./dags:/home/airflow/airflow/dags
      - ./plugins:/home/airflow/airflow/plugins
      - ./python:/home/airflow/airflow/python
      
    ports:
      - "8081:8080"
      - "5001:5000"
    
    networks:
      - pipeline-net

  hadoop:
    image: marcelmittelstaedt/spark_base:latest
    container_name: hadoop
    ports:
      - "8088:8080"
      - "9870:9870"
      - "9864:9864"
      - "8888:8888"
      - "9000:9000"
    
    networks:
      - pipeline-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - pipeline-net

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask-app
    ports:
      - "5002:5000"
    networks:
      - pipeline-net

networks:
  pipeline-net:
    driver: bridge